#ifndef __STATUSCODE_H__
#define __STATUSCODE_H__

#include <stdint.h>

enum statusCode
{
    STATUS_OK = 0,
    STATUS_ERROR,
    STATUS_ERROR_INVALID_PARAMETER,
    STATUS_ERROR_INVALID_STATE,
    STATUS_ERROR_INVALID_DATA,
    STATUS_ERROR_INVALID_SIZE,
    STATUS_ERROR_INVALID_TYPE,
    STATUS_ERROR_INVALID_VALUE,
    STATUS_ERROR_INVALID_ADDRESS,
    STATUS_ERROR_INVALID_OPERATION,
};

#endif