#ifndef _TREE_STATUS_CODE_H_
#define _TREE_STATUS_CODE_H_

#include <stdint.h>

enum tree_status_code_t
{
    TREE_STATUS_OK = 0,
    TREE_STATUS_ERROR,
    TREE_STATUS_ERROR_INVALID_PARAMETER,
    TREE_STATUS_ERROR_INVALID_STATE,
    TREE_STATUS_ERROR_INVALID_DATA,
    TREE_STATUS_ERROR_INVALID_SIZE,
    TREE_STATUS_ERROR_INVALID_TYPE,
    TREE_STATUS_ERROR_INVALID_VALUE,
    TREE_STATUS_ERROR_INVALID_ADDRESS,
    TREE_STATUS_ERROR_INVALID_OPERATION,
};

#endif